### ISSUE TITLE
Openresty 1.19.9.1 compatible with ngx_http_51D_module

### ISSUE THREAD

**Issue by iusik** [51Degrees/device-detection-nginx#4]
Is it posible that openresty 1.19.9.1 is not compatible with ngx_http_51D_module

I was building module like this:
```
make module FIFTYONEDEGREES_NGINX_VERSION=1.19.9
```

```
nginx: [emerg] module "../ngx_http_51D_module.so" is not binary compatible in /etc/nginx/nginx.conf:4
```

**Comment by tungntpham** [comment]
Hi @iusik,

Apologies for the delay on replying to your query. The binary not compatible normally means that the modules are not compiled in the same way, so I suspect there might be an inconsistency in the compilation options being used.

However, currently openresty cannot be used with 51D module as raised [here](https://github.com/51Degrees/device-detection-nginx/issues/2), and we are currently reviewing the decision on support openresty.

We will update as soon as we have further details.

Kind Regards,
