### ISSUE TITLE
Run if statement on $http_x_mobile is not working

### ISSUE THREAD

**Issue by AliAbuArab** [51Degrees/device-detection-nginx#6]
Nginx version: 1.20.0
OS System: Ubuntu 21.10 (impish)

We want to check the user's device, if it Mobile then redirect him to https://m.example.com.
If Desktop then redirect him to https://www.example.com

The code below working as expected:
```
http {
     51D_file_path /etc/nginx/51Degrees-LiteV4.1.hash;
     server {
         ...
         51D_match_single x-mobile IsMobile;
         add_header x-mobile $http_x_mobile;
          ...
     }
}
```
I can see the x-mobile in the respone header.

But when I use the $http_x_mobile in if statement it doesn't work.
```
http {
     51D_file_path /etc/nginx/51Degrees-LiteV4.1.hash;
     server {
         ...
         51D_match_single x-mobile IsMobile;
         if ($http_x_mobile ~ 'True') {
              return 301 https://m.example.com;
          }
          ...
     }
}
```

**Comment by fatima51Degrees** [comment]
Hi AliAbuArab,

We have updated [README.md](https://github.com/51Degrees/device-detection-nginx/blob/main/README.md) to clarify when the value of `header` set by match directives are set. Closing this now.

Regards,
Fatima
