### ISSUE TITLE
undefined symbol: __atomic_compare_exchange_16

### ISSUE THREAD

**Issue by thias** [51Degrees/device-detection-nginx#7]
I've just updated from 4.3.0 to 4.4.0 and the module now fails to load with:
```
nginx: [emerg] dlopen() "/usr/lib64/nginx/modules/ngx_http_51D_module.so" failed (/usr/lib64/nginx/modules/ngx_http_51D_module.so: undefined symbol: __atomic_compare_exchange_16) in /usr/share/nginx/modules/mod-http-51D.conf:1
```

This is with the same RHEL7 OS and build environment as previously, using `-std=gnu11` in CFLAGS (to fix my issues from #1).

Since RHEL7 has a fairly old version of gcc (4.8.5), I have also tried compiling with 9.3.1 from Software Collections, but I got the same undefined symbol.

**Comment by thias** [comment]
After digging some more, I found this: https://stackoverflow.com/questions/26689162/undefined-reference-linker-error-when-using-16-byte-cas-with-gcc

**Comment by tungntpham** [comment]
Hi @thias ,

Many thanks for raising this issue to us. This normally indicates that it cannot resolve the __atomic_compare_exchange_16 symbol. This is declared in the libatomic1 library. Could you check if the libatomic1 library is installed and is included in the LD_LIBRARY_PATH environment variable (if it was installed via a package manager then no need to check) in your target machine?

Kind regards,
Tung.

**Comment by tungntpham** [comment]
Hi @thias,

I hope the solution provided above resolved the issue for you. Please let us know if that isn't the case, else we will proceed to close the issue in the next couple of days. Feel free to reopen if you think otherwise.

Kind regards,
Tung.

**Comment by thias** [comment]
Could this be reopened? As I mentioned, adding `-mcx16` seemed to fix the issue, as it seems to make gcc internally handle that `__atomic_compare_exchange_16`, but now I'm facing the same issue once more because that gcc flag isn't supported on ARM, and I need to recompile nginx for aarch64. So back to square one.

The libatomic library seems to exist, but isn't checked or linked at build time, so even having it installed and available later, still doesn't magically make that symbol be found:
```
$ ldd /usr/lib64/nginx/modules/ngx_http_51D_module.so 
	linux-vdso.so.1 =>  (0x00007fffd9e98000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f539db39000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f539e12a000)
```
For comparison, this is a properly linked 3rd party library:
```
$ ldd /usr/lib64/nginx/modules/ngx_http_geoip2_module.so 
	linux-vdso.so.1 =>  (0x00007ffda746f000)
	libmaxminddb.so.0 => /lib64/libmaxminddb.so.0 (0x00007f9c9ca3f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9c9c671000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9c9ce49000)
```
